In [1]:
import torch
from torch import nn
from d2l import torch as d2l

C:\ProgramData\anaconda3\envs\dd2l\lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(


In [2]:
def pooling2d(X,size,mode='max'):
    p_h, p_w = size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode=='max':
                Y[i][j]=X[i:i+p_h,j:j+p_w].max()
            if mode=='avg':
                Y[i][j]=X[i:i+p_h,j:j+p_w].mean()
    return Y

In [7]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
print(pooling2d(X, (2, 2)))
print(pooling2d(X, (2, 2),'avg'))


tensor([[4., 5.],
        [7., 8.]])
tensor([[2., 3.],
        [5., 6.]])


In [13]:
X=torch.arange(16,dtype=torch.float32).reshape((1,1,4,4,))
pool2d=nn.MaxPool2d(3)#框架中默认步幅和kernal大小相同,从而用于下采样
pool2d(X)

tensor([[[[10.]]]])

In [15]:
#手动指定padding和stride
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [17]:
X=torch.cat((X,X+1,X+2),dim=1)
X.shape #batch,channal,h,w

torch.Size([1, 9, 4, 4])

In [20]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
#仅在维度上做操作,不改变通道数
print(pool2d(X).shape,pool2d(X))

torch.Size([1, 9, 2, 2]) tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 6.,  8.],
          [14., 16.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 8., 10.],
          [16., 18.]],

         [[ 7.,  9.],
          [15., 17.]],

         [[ 8., 10.],
          [16., 18.]],

         [[ 9., 11.],
          [17., 19.]]]])
